package Client_side;

import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author descifrado
 */
public class my_orders extends javax.swing.JFrame 
{
    private DefaultComboBoxModel model;
    private DefaultTableModel tm;
    private final Socket client;
    private final String user_name;
    private DataInputStream dis;
    private DataOutputStream dos;
    
    
    public my_orders(Socket client, String user_name) 
    {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int sht=(int)tk.getScreenSize().getHeight();
        int swd=(int)tk.getScreenSize().getWidth();
        int ht=500;
        int wd=900;
        int x=swd-wd;
        int y=sht-ht;
        this.setBounds(x/2, y/2, wd, ht+30);
        this.setResizable(false);
        this.setTitle("SACRED BAZAR: My Orders");   
        this.client=client;
        this.user_name=user_name;
        try
        {
            dis=new DataInputStream(client.getInputStream());
            dos=new DataOutputStream(client.getOutputStream());
        }
        catch (IOException ex) 
        {
            Logger.getLogger(my_orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOGOLabel = new javax.swing.JLabel();
        TITLELabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UNCB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        MOTB = new javax.swing.JTable();
        HBT = new javax.swing.JButton();
        CSBT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        LOGOLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO_smaller.jpg"))); // NOI18N
        jPanel1.add(LOGOLabel);
        LOGOLabel.setBounds(60, 10, 60, 60);

        TITLELabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        TITLELabel.setText("MY ORDERS");
        jPanel1.add(TITLELabel);
        TITLELabel.setBounds(130, 20, 260, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SIGNED IN AS:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 30, 110, 20);

        UNCB.setBackground(new java.awt.Color(215, 218, 243));
        UNCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UNCB.setModel(new DefaultComboBoxModel());
        UNCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNCBActionPerformed(evt);
            }
        });
        jPanel1.add(UNCB);
        UNCB.setBounds(670, 20, 180, 40);

        MOTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "PRICE", "QUANTITY", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(MOTB);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(22, 90, 860, 280);

        HBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HBT.setText("HOME");
        HBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HBTActionPerformed(evt);
            }
        });
        jPanel1.add(HBT);
        HBT.setBounds(120, 420, 150, 40);

        CSBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CSBT.setText("ALL PRODUCTS");
        CSBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSBTActionPerformed(evt);
            }
        });
        jPanel1.add(CSBT);
        CSBT.setBounds(640, 420, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BAckground.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-6, -6, 910, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UNCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNCBActionPerformed
        String select=(String)model.getSelectedItem();
        if(select.equals("Profile"))
        {
            try
            {
                new cust_profile(client,user_name).show();
            }
            catch (IOException ex)
            {
                Logger.getLogger(my_cart.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        if(select.equals("My Cart"))
        {
            new my_cart(client,user_name).show();
            this.dispose();
        }
        if(select.equals("Log out"))
        {
            int i=JOptionPane.showConfirmDialog(this,"Are You Sure You Want To Log out?",null,JOptionPane.YES_NO_OPTION);
            if(i==0)
            {
                try
                {
                    String request="Log_out";
                    dos.writeUTF(request);
                    String response=dis.readUTF();
                    if(response.equals("done"))
                    {
                        JOptionPane.showMessageDialog(this, "Successfully Logged Out");
                        new MainPage().show();
                        this.dispose();
                    }
                }
                catch (IOException ex)
                {
                    System.out.println("Client Error"+ex.getMessage());
                    Logger.getLogger(first_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_UNCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        model=(DefaultComboBoxModel)UNCB.getModel();
        tm=(DefaultTableModel) MOTB.getModel();
        model.addElement(user_name);
        model.addElement("Profile");
        model.addElement("My Cart");
        model.addElement("Log out");
        try 
        {
            dos.writeUTF("MyOrder");
            String response=dis.readUTF();
            String row[]=response.split("@");
            int l=row.length;
            for(int i=0;i<l;i++)
            {
                String data[]=row[i].split("`");
                tm.addRow(new Object[]{data[0],data[1],data[2],data[3],data[4]});
            }            
        }
        catch (IOException ex) 
        {
            Logger.getLogger(my_orders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void HBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HBTActionPerformed
        try
        {
            // TODO add your handling code here:
            new first_page(client, user_name).show();
        }
        catch (IOException ex) 
        {
            Logger.getLogger(my_orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_HBTActionPerformed

    private void CSBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSBTActionPerformed
        try
        {
            // TODO add your handling code here:
            new All_Products(client, user_name).show();
        }
        catch (IOException ex) 
        {
            Logger.getLogger(my_orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_CSBTActionPerformed

    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CSBT;
    private javax.swing.JButton HBT;
    private javax.swing.JLabel LOGOLabel;
    private javax.swing.JTable MOTB;
    private javax.swing.JLabel TITLELabel;
    private javax.swing.JComboBox UNCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
