
package javaapplication7;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {
    
    public static int TotalCost=0;
    public static Socket socket    = null; 
    public static DataOutputStream out     = null; 
    public static DataInputStream inn =null;
    public static ObjectOutputStream output=null;
    public static  ObjectInputStream input =null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        try 
        {socket = new Socket("192.168.43.233",7000); 
            
            inn=new DataInputStream(socket.getInputStream());
            out    = new DataOutputStream(socket.getOutputStream()); 
            output=new ObjectOutputStream(socket.getOutputStream());
            input = new ObjectInputStream(socket.getInputStream());
            } 
        catch(UnknownHostException u) 
        { 
            System.out.println(u); 
        } 
        catch(IOException i) 
        { 
            System.out.println(i); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phnnum = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        usrname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        passwd = new javax.swing.JPasswordField();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1373, 943));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1150, 60, 90, 25);

        jButton2.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        jButton2.setText("Wanna to sell your product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 280, 410, 160);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("SignUp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 200, 110, 60);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Register");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 770, 120, 27);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 320, 27, 14);

        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 420, 70, 14);

        jLabel4.setText("Email-Id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 480, 38, 14);

        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 580, 39, 14);
        getContentPane().add(name);
        name.setBounds(530, 310, 114, 20);

        phnnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnnumActionPerformed(evt);
            }
        });
        getContentPane().add(phnnum);
        phnnum.setBounds(530, 420, 114, 20);
        getContentPane().add(mail);
        mail.setBounds(530, 480, 114, 20);

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Enter Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 60, 240, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 60, 140, 30);
        getContentPane().add(usr);
        usr.setBounds(440, 60, 94, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 130, 1291, 10);

        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 530, 46, 14);
        getContentPane().add(address);
        address.setBounds(530, 570, 114, 20);

        jLabel9.setText("Age");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 630, 19, 14);
        getContentPane().add(age);
        age.setBounds(530, 620, 114, 20);

        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(350, 370, 48, 14);
        getContentPane().add(usrname);
        usrname.setBounds(530, 370, 114, 20);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(530, 530, 114, 20);

        jLabel10.setText("Gender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 690, 35, 14);
        getContentPane().add(gender);
        gender.setBounds(530, 680, 114, 20);
        getContentPane().add(passwd);
        passwd.setBounds(910, 60, 160, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Loginclass lg=new Loginclass();
int right=0;
String cmd="41Select * from user_info where USERNAME ='"+ usr.getText()+"' and PASSWORD ='"+passwd.getText()+"' ;";
       
  int Ans=0;

            try {
             Ans=lg.Reply(cmd,0,1);
            System.out.println("ans "+Ans);
            
            
          
        } catch (ClassNotFoundException ex) {
            System.out.println("hello1");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } 
        if(Ans!=0)
        {
          HomePage home=new HomePage();  
          home.setVisible(true);
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Wrong Details!! Please enter right username and password .");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Loginclass lg=new Loginclass();
String cmd="40Insert into  user_info values('" + usrname.getText() + "121','" + usrname.getText()+ "','" +name.getText()+ "','" + phnnum.getText() + "','" + mail.getText() + "','" + String.valueOf(password.getPassword()) + "','" + address.getText() + "','" + gender.getText()+ "','" +age.getText()+"');";
 int Ans=0;

        try { 
            Ans=lg.Reply(cmd,1,0);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginShop.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(Ans!=0)
        {
          JOptionPane.showMessageDialog(null,"You are successfully registered.");
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Wrong Details!! Please enter right username and password .");
        }

        




// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void phnnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnnumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        LoginShop Ls=new LoginShop();
        Ls.setVisible(true);





    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phnnum;
    private javax.swing.JTextField usr;
    private javax.swing.JTextField usrname;
    // End of variables declaration//GEN-END:variables
}
